/*
 * NETCAP - Traffic Analysis Framework
 * Copyright (c) Philipp Mieden <dreadl0ck [at] protonmail [dot] ch>
 * License: GNU General Public License v3.0
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package rules

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/expr-lang/expr/vm"
	"gopkg.in/yaml.v2"

	"github.com/dreadl0ck/netcap/internal/filter"
	"github.com/dreadl0ck/netcap/types"
)

// Rule represents a detection rule that can be evaluated against audit records.
type Rule struct {
	// Name is a unique identifier for the rule
	Name string `yaml:"name"`

	// Description provides human-readable information about the rule
	Description string `yaml:"description"`

	// Type specifies which audit record type this rule applies to (e.g., "TCP", "HTTP")
	Type string `yaml:"type"`

	// Expression is the expr-lang expression to evaluate
	Expression string `yaml:"expression"`

	// Severity indicates the importance of alerts generated by this rule
	// Valid values: low, medium, high, critical
	Severity string `yaml:"severity"`

	// MITRE contains MITRE ATT&CK technique IDs associated with this rule
	MITRE []string `yaml:"mitre"`

	// Tags are custom labels for categorizing rules
	Tags []string `yaml:"tags"`

	// Enabled determines whether this rule is active
	Enabled bool `yaml:"enabled"`

	// Threshold is the number of times this rule must match before triggering an alert
	// If 0 or 1, alert is triggered immediately on first match (default behavior)
	Threshold int `yaml:"threshold,omitempty"`

	// ThresholdWindow is the time window (in seconds) within which the threshold must be reached
	// Only applicable when Threshold > 1. Default is 60 seconds (1 minute)
	ThresholdWindow int `yaml:"threshold_window,omitempty"`

	// DistinctField enables cardinality-based detection: instead of counting raw
	// matches, the engine counts the number of DISTINCT values of this field
	// observed per source IP within ThresholdWindow. When the distinct count
	// reaches DistinctThreshold, an alert fires.
	//
	// This expresses the AA26-231A "internal enumeration" hunt shape: one source
	// touching many distinct controllers on port 102, once each. For example,
	// DistinctField: "DstIP" with DistinctThreshold: 5 fires when a single
	// source contacts 5+ distinct destinations within the window.
	//
	// The field name must be a top-level field of the record type (e.g. "DstIP").
	DistinctField string `yaml:"distinct_field,omitempty"`

	// DistinctThreshold is the number of distinct DistinctField values (per source)
	// required within ThresholdWindow before an alert fires. Only applicable when
	// DistinctField is set. Defaults to 2 if DistinctField is set but this is <= 1.
	DistinctThreshold int `yaml:"distinct_threshold,omitempty"`

	// Actions are response actions to execute when this rule matches and generates an alert.
	// These are automated responses like blocking IPs via iptables.
	Actions []*ResponseAction `yaml:"actions,omitempty"`

	// Sequence requires an earlier record to have been observed before this
	// rule's own expression can raise an alert. It expresses "B after A within
	// a window, for the same group", such as a write to a register that the
	// same source read minutes earlier.
	//
	// When set, the sequence gate is applied first; Threshold and DistinctField
	// then behave exactly as they do for an ungated rule.
	Sequence *Sequence `yaml:"sequence,omitempty"`

	// compiled is the compiled expression program (not serialized)
	compiled *vm.Program
}

// Sequence configures ordered, grouped correlation for a rule.
type Sequence struct {
	// After is the expression identifying the earlier record. It is evaluated
	// against the same record type as the rule.
	After string `yaml:"after"`

	// GroupBy lists top-level record fields whose values must be equal for the
	// earlier and triggering records to be considered related. Grouping is
	// exact equality: it cannot express range overlap.
	GroupBy []string `yaml:"group_by"`

	// Within is how many seconds the earlier record stays eligible. Default 60.
	Within int `yaml:"within,omitempty"`

	// compiledAfter is the compiled After program (not serialized)
	compiledAfter *vm.Program
}

// Validate checks that a sequence is usable before rules are compiled.
func (s *Sequence) Validate() error {
	if s.After == "" {
		return fmt.Errorf("sequence requires an after expression")
	}
	if len(s.GroupBy) == 0 {
		// Without a group key the gate would correlate unrelated hosts.
		return fmt.Errorf("sequence requires at least one group_by field")
	}
	for _, field := range s.GroupBy {
		if field == "" {
			return fmt.Errorf("sequence group_by contains an empty field name")
		}
	}
	if s.Within < 0 {
		return fmt.Errorf("sequence within cannot be negative")
	}
	// Guard against seconds/nanoseconds confusion overflowing the window into a
	// negative duration, which would silently stop the rule from ever firing.
	if s.Within > maxSequenceWithinSeconds {
		return fmt.Errorf("sequence within %d exceeds the %d second maximum", s.Within, maxSequenceWithinSeconds)
	}
	return nil
}

// maxSequenceWithinSeconds caps the eligibility window at 30 days.
const maxSequenceWithinSeconds = 30 * 24 * 60 * 60

// window returns the configured eligibility window.
func (s *Sequence) window() time.Duration {
	if s.Within <= 0 {
		return time.Minute
	}
	return time.Duration(s.Within) * time.Second
}

// ResponseAction defines an automated response to a rule match.
type ResponseAction struct {
	// Type is the action type (iptables_block, iptables_reject, iptables_rate_limit, iptables_log)
	Type string `yaml:"type"`

	// Config contains action-specific configuration
	Config map[string]any `yaml:"config,omitempty"`

	// Enabled allows disabling specific actions (default: true if omitted)
	Enabled *bool `yaml:"enabled,omitempty"`
}

// IsEnabled returns true if the action is enabled (default is true).
func (a *ResponseAction) IsEnabled() bool {
	if a.Enabled == nil {
		return true // Default to enabled
	}
	return *a.Enabled
}

// Validate checks if the response action has a valid type.
func (a *ResponseAction) Validate() error {
	switch a.Type {
	case "iptables_block", "iptables_reject", "iptables_rate_limit", "iptables_log":
		return nil
	default:
		return fmt.Errorf("unknown response action type: %s", a.Type)
	}
}

// Config holds a collection of rules loaded from a YAML file.
type Config struct {
	Description string  `yaml:"description"`
	Rules       []*Rule `yaml:"rules"`
}

// LoadRulesFromFile loads rules from a YAML file.
func LoadRulesFromFile(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read rules file: %w", err)
	}

	var config Config
	err = yaml.Unmarshal(data, &config)
	if err != nil {
		return nil, fmt.Errorf("failed to parse rules YAML: %w", err)
	}

	return &config, nil
}

// LoadRulesFromDirectory loads all rule files from a directory and returns a merged configuration.
func LoadRulesFromDirectory(dirPath string) (*Config, error) {
	config := &Config{
		Rules: []*Rule{},
	}

	entries, err := os.ReadDir(dirPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read rules directory: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".yml") {
			continue
		}

		filePath := filepath.Join(dirPath, entry.Name())
		fileConfig, err := LoadRulesFromFile(filePath)
		if err != nil {
			return nil, fmt.Errorf("failed to load rules from %s: %w", entry.Name(), err)
		}

		config.Rules = append(config.Rules, fileConfig.Rules...)
	}

	return config, nil
}

// CompileRules compiles all rule expressions in the configuration.
func CompileRules(config *Config) error {
	for i, rule := range config.Rules {
		// Validate sequences even when disabled: hunt templates ship disabled,
		// and a broken one must not surface only when an operator enables it.
		if rule.Sequence != nil {
			if err := rule.Sequence.Validate(); err != nil {
				return fmt.Errorf("rule %s: %w", rule.Name, err)
			}
		}

		if !rule.Enabled {
			continue
		}

		if rule.Expression == "" {
			return fmt.Errorf("rule %s has empty expression", rule.Name)
		}

		// Convert type string to types.Type
		recordType, err := parseRecordType(rule.Type)
		if err != nil {
			return fmt.Errorf("rule %s: %w", rule.Name, err)
		}

		// Compile the expression
		program, err := filter.CompileExpression(rule.Expression, recordType)
		if err != nil {
			return fmt.Errorf("failed to compile rule %s: %w", rule.Name, err)
		}

		config.Rules[i].compiled = program

		if seq := rule.Sequence; seq != nil {
			if err = validateGroupFields(seq.GroupBy, recordType); err != nil {
				return fmt.Errorf("rule %s: %w", rule.Name, err)
			}
			after, err := filter.CompileExpression(seq.After, recordType)
			if err != nil {
				return fmt.Errorf("failed to compile sequence for rule %s: %w", rule.Name, err)
			}
			config.Rules[i].Sequence.compiledAfter = after
		}
	}

	return nil
}

// EvaluateRule evaluates a rule against an audit record and returns an alert if it matches.
func EvaluateRule(rule *Rule, record types.AuditRecord) (*types.Alert, error) {
	if !rule.Enabled {
		return nil, nil
	}

	if rule.compiled == nil {
		return nil, fmt.Errorf("rule %s is not compiled", rule.Name)
	}

	// Evaluate the expression
	match, err := filter.EvaluateExpression(rule.compiled, record)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate rule %s: %w", rule.Name, err)
	}

	if !match {
		return nil, nil
	}

	// Ensure tags is never nil (use empty slice if nil)
	tags := rule.Tags
	if tags == nil {
		tags = []string{}
	}

	// Create alert
	alert := &types.Alert{
		Timestamp:       time.Now().UnixNano(),
		Name:            rule.Name,
		Description:     rule.Description,
		RuleName:        rule.Name,
		RecordType:      record.NetcapType().String(),
		Severity:        rule.Severity,
		Tags:            tags,
		RuleExpression:  rule.Expression,
		Threshold:       int32(rule.Threshold),
		ThresholdWindow: int32(rule.ThresholdWindow),
	}

	// Set MITRE ATT&CK IDs (join multiple IDs)
	if len(rule.MITRE) > 0 {
		alert.MITRE = strings.Join(rule.MITRE, ",")
	}

	// Extract source and destination from record
	alert.SrcIP = record.Src()
	alert.DstIP = record.Dst()

	// Try to marshal the record as JSON for context
	recordJSON, err := json.Marshal(record)
	if err == nil {
		alert.MatchedRecord = string(recordJSON)
	}

	return alert, nil
}

// parseRecordType converts a type string (e.g., "TCP", "HTTP") to types.Type.
func parseRecordType(typeStr string) (types.Type, error) {
	// Add NC_ prefix if not present
	if !strings.HasPrefix(typeStr, "NC_") {
		typeStr = "NC_" + typeStr
	}

	// Look up the type value
	typeValue, ok := types.Type_value[typeStr]
	if !ok {
		return 0, fmt.Errorf("unknown record type: %s", typeStr)
	}

	return types.Type(typeValue), nil
}

// ValidateSeverity checks if a severity string is valid.
func ValidateSeverity(severity string) bool {
	switch strings.ToLower(severity) {
	case "info", "low", "medium", "high", "critical":
		return true
	default:
		return false
	}
}
