#!/bin/sh

set -eu

mode="${1:-generate}"
case "$mode" in
    generate|-check) ;;
    *) echo "usage: $0 [generate|-check]" >&2; exit 2 ;;
esac

root=$(git rev-parse --show-toplevel)
tmp=$(mktemp -d "${TMPDIR:-/tmp}/netcap-rust-licenses.XXXXXX")
trap 'rm -rf "$tmp"' EXIT INT TERM

fetch() {
    curl --fail --location --retry 3 "$1" --output "$2"
}

about="$tmp/cargo-about"
if command -v cargo-about >/dev/null 2>&1 && [ "$(cargo-about --version)" = "cargo-about 0.9.2" ]; then
    about=$(command -v cargo-about)
else
    case "$(uname -s)-$(uname -m)" in
        Darwin-arm64)
            target="aarch64-apple-darwin"
            checksum="ae72f0df0c399a1e96336f696fa55b1b28679fd725632eba8cf8e4568467cc3e"
            ;;
        Linux-x86_64)
            target="x86_64-unknown-linux-musl"
            checksum="9099a59e820c38a68b9d65f300662a567d56562f9a10f6aa4c7e86c17c2566af"
            ;;
        Linux-aarch64)
            target="aarch64-unknown-linux-musl"
            checksum="af5169282fb6f84e13471493f405437e43ac517744c9ae12fbe2cdf0a6f0e5a8"
            ;;
        *)
            echo "install cargo-about 0.9.2 for $(uname -s)-$(uname -m)" >&2
            exit 1
            ;;
    esac
    archive="$tmp/cargo-about.tar.gz"
    fetch "https://github.com/EmbarkStudios/cargo-about/releases/download/0.9.2/cargo-about-0.9.2-${target}.tar.gz" "$archive"
    printf '%s  %s\n' "$checksum" "$archive" | shasum -a 256 -c -
    tar -xzf "$archive" -C "$tmp"
    about="$tmp/cargo-about-0.9.2-${target}/cargo-about"
fi

fetch "https://github.com/google/magika/archive/refs/tags/cli/v1.0.2.tar.gz" "$tmp/magika.tar.gz"
fetch "https://github.com/VirusTotal/yara-x/archive/refs/tags/v1.14.0.tar.gz" "$tmp/yara-x.tar.gz"
printf '%s  %s\n' "bae42b31c8f419f34043cc2cf26fa42d2ade7f7c91e2fb54919914432f799699" "$tmp/magika.tar.gz" | shasum -a 256 -c -
printf '%s  %s\n' "3a251473fc75673196b0acd678893f90478b83a6dd5ce255f53e2ac086a50254" "$tmp/yara-x.tar.gz" | shasum -a 256 -c -
tar -xzf "$tmp/magika.tar.gz" -C "$tmp"
tar -xzf "$tmp/yara-x.tar.gz" -C "$tmp"

generate() {
    "$about" generate \
        --manifest-path "$1" \
        --config "$root/legal/rust-about.toml" \
        --locked --fail \
        --output-file "$2" \
        "$root/legal/rust-about.hbs"
}

generate "$tmp/magika-cli-v1.0.2/rust/cli/Cargo.toml" "$tmp/magika.txt"
generate "$tmp/yara-x-1.14.0/capi/Cargo.toml" "$tmp/yara-x.txt"

generated="$tmp/THIRD_PARTY_RUST_LICENSES.txt"
{
    printf '%s\n\n' 'NETCAP BUNDLED RUST THIRD-PARTY LICENSES'
    printf '%s\n' 'Generated from the locked dependency graphs for Magika CLI 1.0.2 and YARA-X C API 1.14.0.'
    printf '%s\n\n' 'Do not edit this file manually. Run zeus/scripts/rust-licenses.sh.'
    printf '%s\n%s\n\n' '################################################################################' 'MAGIKA CLI 1.0.2'
    cat "$tmp/magika.txt"
    printf '%s\n%s\n\n' '################################################################################' 'YARA-X C API 1.14.0'
    cat "$tmp/yara-x.txt"
} > "$generated"

output="$root/legal/THIRD_PARTY_RUST_LICENSES.txt"
if [ "$mode" = "-check" ]; then
    cmp "$generated" "$output" || {
        echo "$output is stale; run zeus/scripts/rust-licenses.sh" >&2
        exit 1
    }
    echo "Rust license bundle is current"
else
    cp "$generated" "$output"
    echo "wrote $output"
fi
