/*
 * NETCAP - Traffic Analysis Framework
 * Copyright (c) 2017-2020 Philipp Mieden <dreadl0ck [at] protonmail [dot] ch>
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package service

var servicesByPortsUDP = map[int32]string{
	53:    "dns",
	9100:  "hbn3",
	10001: "ubiquiti-discovery",
	199:   "smux",
	1677:  "groupwise",
	88:    "kerberos",
	1900:  "ssdp",
	491:   "go-login",
	70:    "gopher",
	308:   "novastor-backup",
	3872:  "oem-agent",
	2775:  "smpp",
	1241:  "nessus",
	1527:  "oracle",
	5999:  "cvsup",
	3389:  "ms-wbt-server",
	1812:  "radius",
	1604:  "icabrowser",
	3333:  "dec-notes",
	2368:  "opentable",
	1344:  "icap",
	5060:  "sip",
	1414:  "ibm-mqseries",
	8880:  "cddbp",
	18182: "opsec-ufp",
	3659:  "apple-sasl",
	628:   "qmqp",
	2592:  "netrek",
	1319:  "amx-icsp",
	79:    "finger",
	9090:  "websm",
	13:    "daytime",
	445:   "microsoft-ds",
	5631:  "pcanywheredata",
	10080: "amanda",
	161:   "snmp",
	3970:  "lanrev-agent",
	2583:  "mon",
	4559:  "hylafax",
	174:   "mailq",
	5405:  "netsupport",
	1194:  "openvpn",
	37:    "time",
	873:   "rsync",
	531:   "chat",
	3288:  "cops",
	8160:  "patrol",
	5672:  "amqp",
	2967:  "ssc-agent",
	860:   "iscsi",
	655:   "tinc",
	26000: "quake",
	706:   "silc",
	523:   "ibm-db2",
	1723:  "pptp",
	23:    "telnet",
	3306:  "mysql",
	7:     "echo",
	9909:  "domaintime",
	524:   "ncp",
	2512:  "citrix-ima",
	7279:  "citrix-licensing",
	2628:  "dict",
	1540:  "rds",
	500:   "isakmp",
	674:   "acap",
	1923:  "spice",
	2401:  "cvspserver",
	4443:  "pharos",
	5093:  "sentinel-lm",
	1058:  "nim",
	1721:  "caicci",
	407:   "timbuktu",
	504:   "citadel",
	3493:  "nut",
	389:   "ldap",
}

var servicesByPortsTCP = map[int32]string{
	5672:  "amqp",
	2967:  "ssc-agent",
	860:   "iscsi",
	655:   "tinc",
	26000: "quake",
	706:   "silc",
	523:   "ibm-db2",
	1723:  "pptp",
	23:    "telnet",
	3306:  "mysql",
	7:     "echo",
	9909:  "domaintime",
	524:   "ncp",
	2512:  "citrix-ima",
	7279:  "citrix-licensing",
	2628:  "dict",
	1540:  "rds",
	500:   "isakmp",
	674:   "acap",
	1923:  "spice",
	810:   "fcp",
	2401:  "cvspserver",
	4443:  "pharos",
	5093:  "sentinel-lm",
	1058:  "nim",
	1721:  "caicci",
	504:   "citadel",
	407:   "timbuktu",
	199:   "smux",
	1677:  "groupwise",
	88:    "kerberos",
	1900:  "ssdp",
	491:   "go-login",
	70:    "gopher",
	308:   "novastor-backup",
	6432:  "pgbouncer",
	3872:  "oem-agent",
	2775:  "smpp",
	1241:  "nessus",
	1527:  "oracle",
	5999:  "cvsup",
	3389:  "ms-wbt-server",
	1812:  "radius",
	1604:  "icabrowser",
	3333:  "dec-notes",
	2368:  "opentable",
	1344:  "icap",
	5060:  "sip",
	1414:  "ibm-mqseries",
	8880:  "cddbp",
	18182: "opsec-ufp",
	3659:  "apple-sasl",
	628:   "qmqp",
	2592:  "netrek",
	1319:  "amx-icsp",
	79:    "finger",
	9090:  "websm",
	13:    "daytime",
	5631:  "pcanywheredata",
	445:   "microsoft-ds",
	10080: "amanda",
	161:   "snmp",
	2583:  "mon",
	3970:  "lanrev-agent",
	4559:  "hylafax",
	174:   "mailq",
	5405:  "netsupport",
	1194:  "openvpn",
	37:    "time",
	873:   "rsync",
	531:   "chat",
	3288:  "cops",
	8160:  "patrol",
	110:   "pop3-proxy",
	443:   "tls",
	13724: "vnetd",
	2002:  "d-mp",
	2001:  "d-mp",
	4447:  "jboss-remoting",
	10001: "ubiquiti-discovery",
	789:   "epoptes-client",
	5432:  "PostgreSQL",
	502:   "modbus",
	3300:  "ceph",
	6789:  "ceph",
	8069:  "openerp",
	61616: "apachemq",
	6379:  "redis",
	9418:  "git-daemon",
	5061:  "sip",
	8834:  "nessus",
	4321:  "whois",
	80:    "http",
	389:   "ldap",
	21:    "ftp",
	9127:  "java-message-service",
	783:   "spamassassin",
	3493:  "nut",
	444:   "snpp",
	25:    "smtp",
	465:   "smtp",
	587:   "smtp",
	143:   "imap",
	// VNC by default uses TCP port 5900+N, where N is the display number (usually :0 for a physical display).
	5901:  "vnc",
	5902:  "vnc",
	5903:  "vnc",
	5904:  "vnc",
	5905:  "vnc",
	27017: "mongodb",
	27018: "mongodb",
	123:   "ntp",
	5555:  "adb",
	1080:  "socks4",

	// 0: "atalla",
	// 0: "lastfm",
	// 0: "transbase",
	// 0: "unitrends-backup",
	// 0: "AirHID",
	// 0: "shoutirc",
	// 0: "tina",
	// 0: "qcheck",
	// 0: "barracuda-bcp",
	// 0: "ipsi",
	// 0: "listserv",
	// 0: "seti-proxy",
	// 0: "tor-orport",
	// 0: "honeywell-ripsd",
	// 0: "honeypot",
	// 0: "as-sts",
	// 0: "sap-gui",
	// 0: "fms-core",
	// 0: "palm-hotsync",
	// 0: "klogin",
	// 0: "smtp",
	// 0: "dsr-video",
	// 0: "winlog",
	// 0: "pycharm",
	// 0: "pvx",
	// 0: "soap",
	// 0: "syncplay-json",
	// 0: "teradata",
	// 0: "g-data-sec",
	// 0: "mailq",
	// 0: "ibank2",
	// 0: "airdroid",
	// 0: "kmldonkey",
	// 0: "epmd",
	// 0: "nutcracker",
	// 0: "topdesk",
	// 0: "mapreduce",
	// 0: "retrospect",
	// 0: "solidworks-remotesolve",
	// 0: "lexmark-objectstore",

	// 0: "isymphony-client",
	// 0: "r1soft-cdp",
	// 0: "jicp",
	// 0: "byond",
	// 0: "svrloc",
	// 0: "ident",
	// 0: "netrek",
	// 0: "silkroad-online",
	// 0: "3m-sip",
	// 0: "uucp",
	// 0: "rpcapd",

	// 0: "intelatrac",
	// 0: "tunnelvision",
	// 0: "gnupg",
	// 0: "dnet-keyproxy",
	// 0: "magent",

	// 0: "metasploit-xmlrpc",
	// 0: "bitcoin-jsonrpc",
	// 0: "urp",
	// 0: "qnap-transcode",
	// 0: "weprint",
	// 0: "abc",
	// 0: "pgbouncer",

	// 0: "diskmonitor",
	// 0: "pcanywheredata",
	// 0: "pblocald",
	// 0: "rtrdb",
	// 0: "h323q931",
	// 0: "acap",
	// 0: "chilliworx",
	// 0: "mpich2",
	// 0: "nntp-proxy",
	// 0: "visitview",
	// 0: "foolscap",
	// 0: "olsrd-jsoninfo",
	// 0: "ilo-console",
	// 0: "netstat",
	// 0: "netbus",
	// 0: "zeiss-axio",
	// 0: "melange",
	// 0: "tor-socks",
	// 0: "cpu",
	// 0: "thrift-binary",
	// 0: "ilo",
	// 0: "nimbud-netmon",
	// 0: "relp",
	// 0: "webdav",
	// 0: "gnuserv",
	// 0: "pigpio",
	// 0: "cisco-smartinstall",
	// 0: "vp3",
	// 0: "airserv-ng",
	// 0: "varnish-cli",
	// 0: "dps-shell",
	// 0: "clementine-remote",
	// 0: "efi-webtools",
	// 0: "as-servermap",
	// 0: "vzagent",
	// 0: "gamebots",
	// 0: "jetadmin",

	// 0: "mohaa",
	// 0: "bzfs",
	// 0: "ssl/imap",
	// 0: "oracle-db-rmi",
	// 0: "intermapper",
	// 0: "cisco-lm",
	// 0: "ratnj",
	// 0: "bandwidth-test",
	// 0: "citrix-ica",
	// 0: "inetd",
	// 0: "oracle-tns",
	// 0: "gcs-clientgw",
	// 0: "transferimg",
	// 0: "sybase-backup",
	// 0: "appleevents",
	// 0: "riak-pbc",
	// 0: "tcpmux",
	// 0: "unicorn-ils",
	// 0: "softether-rpc",
	// 0: "midas",
	// 0: "mserv",
	// 0: "intermec-bri",

	// 0: "fastobjects-db",
	// 0: "enemyterritory",
	// 0: "usher",
	// 0: "oracle-nm",
	// 0: "apple-iphoto",
	// 0: "infopark",
	// 0: "ajp12",
	// 0: "xboxdebug",
	// 0: "netbackup",
	// 0: "netwareip",
	// 0: "xdmcp",
	// 0: "valentinadb",
	// 0: "inspircd-spanning-tree",
	// 0: "loginserver",
	// 0: "oracle-vs",
	// 0: "progress",
	// 0: "trustwave",
	// 0: "afbackup",
	// 0: "riegl-license",
	// 0: "smtp-proxy",
	// 0: "james-admin",

	// 0: "flexlm",
	// 0: "ibm-db2",
	// 0: "donkey",
	// 0: "shell",
	// 0: "wesnoth",
	// 0: "kapow-robot",
	// 0: "print-monitor",
	// 0: "valve-steam",
	// 0: "asus-transfer",
	// 0: "login",
	// 0: "impress-remote",
	// 0: "millennium",
	// 0: "minecraft",
	// 0: "freelancer",
	// 0: "parallels-server",
	// 0: "eth-jsonrpc",
	// 0: "iscsi",
	// 0: "honeywell-confd",
	// 0: "sassafras",
	// 0: "ilo-vm",

	// 0: "citadel",
	// 0: "jdwp",
	// 0: "lcdproc",
	// 0: "mtap",
	// 0: "pc-anywhere",
	// 0: "NetMotionMobility",
	// 0: "websense-eim",
	// 0: "honeywell-hscodbcn",
	// 0: "H.323/Q.931",
	// 0: "pbmasterd",
	// 0: "lirc",
	// 0: "tally-census",
	// 0: "bittorrent",
	// 0: "daytime",
	// 0: "meterpreter",
	// 0: "complex-link",
	// 0: "ericom",
	// 0: "code42-messaging",
	// 0: "slimp3",
	// 0: "autonomic-mrad",
	// 0: "BackOrifice",
	// 0: "concertotimesync",
	// 0: "xmbmon",
	// 0: "hnap",
	// 0: "ssl/pop3",
	// 0: "workrave",
	// 0: "laserfiche",
	// 0: "qconn",
	// 0: "netprobe",
	// 0: "amanda",
	// 0: "backdoor",
	// 0: "netop",
	// 0: "H.323-gatekeeper",
	// 0: "vspe",
	// 0: "xtunnels",
	// 0: "ndmp",
	// 0: "keriopfservice",
	// 0: "vmware-print",
	// 0: "anynet-sna",
	// 0: "AndroMouse",
	// 0: "intranetchat",
	// 0: "ipmi-advertiserd",
	// 0: "icabrowser",
	// 0: "quake3-master",
	// 0: "kumo-server",
	// 0: "bru",
	// 0: "remoting",
	// 0: "syncsort-cmagent",
	// 0: "sysinfo",
	// 0: "digitalwatchdog",
	// 0: "greenplum",
	// 0: "H.323-gatekeeper-discovery",
	// 0: "maya",
	// 0: "poweroff",
	// 0: "sophos",
	// 0: "nvidia-update",
	// 0: "desktop-central",
	// 0: "ms-sql-s",
	// 0: "enistic-manager",
	// 0: "igel-remote",
	// 0: "netbios-ssn",
	// 0: "pwdgen",
	// 0: "zos-commserver",
	// 0: "athinfod",
	// 0: "bf2rcon",
	// 0: "directupdate",
	// 0: "epp",
	// 0: "tunnel-test",
	// 0: "roku-remote",
	// 0: "sgms",
	// 0: "zftp-admin",
	// 0: "wincomm",
	// 0: "webcache",
	// 0: "kazaa-peerpoint",
	// 0: "postgrey",
	// 0: "mcms-command",
	// 0: "siemens-xtrace",
	// 0: "cassandra-native",
	// 0: "zebra",
	// 0: "murmur",
	// 0: "directconnect",
	// 0: "logevent",
	// 0: "rsync",
	// 0: "multiplicity",
	// 0: "satstrat",
	// 0: "ichat",
	// 0: "java-cim",
	// 0: "lsx",
	// 0: "rmmd",
	// 0: "amx-icsp",
	// 0: "ecopy",
	// 0: "printeron",
	// 0: "ws-discovery",
	// 0: "asterisk",
	// 0: "filemaker-xdbc",
	// 0: "mu-connect",
	// 0: "raid-mon",
	// 0: "wikidpad",
	// 0: "serialnumber",
	// 0: "telecom-misc",
	// 0: "mitsubishi-qj71e71",
	// 0: "control-m",
	// 0: "sumatra-ds",
	// 0: "sqlmonitor",
	// 0: "dgld",
	// 0: "tcsd",
	// 0: "vsFTPd",
	// 0: "ppp",
	// 0: "aspi",
	// 0: "kerberos-sec",
	// 0: "synobtrfsreplicad",
	// 0: "pafserver",
	// 0: "haproxy-stats",
	// 0: "snapmirror",
	// 0: "kvm",
	// 0: "trinitycore",
	// 0: "tor-info",
	// 0: "docker",
	// 0: "sybase-monitor",
	// 0: "radmin",
	// 0: "ldminfod",
	// 0: "mu-game",
	// 0: "teamviewer",
	// 0: "kdb",
	// 0: "fcgiwrap",
	// 0: "argus",
	// 0: "concertosendlog",
	// 0: "precomd",
	// 0: "weather",
	// 0: "bzr",
	// 0: "xfs",
	// 0: "telnet",
	// 0: "helpdesklog",
	// 0: "qnap-rtrr",
	// 0: "fcp",
	// 0: "monop",
	// 0: "wingate-control",
	// 0: "h2-pg",
	// 0: "rbnb",
	// 0: "minecraft-votifier",
	// 0: "wcbackup",
	// 0: "iperf3",
	// 0: "nsi",
	// 0: "ups",
	// 0: "crestron-xsig",
	// 0: "fcpv2",
	// 0: "sieve",
	// 0: "starutil",
	// 0: "brio",
	// 0: "pfservice",
	// 0: "nimp",
	// 0: "gopher-proxy",
	// 0: "icap",
	// 0: "winbox",
	// 0: "jmond",
	// 0: "nuuo-vnc",
	// 0: "netsaint",
	// 0: "sauerbraten",
	// 0: "nim",
	// 0: "radius",
	// 0: "bitcoin",
	// 0: "eve-online",
	// 0: "dlswpn",
	// 0: "radmind",
	// 0: "xml-rpc",
	// 0: "msexchange-logcopier",
	// 0: "crestron-control",
	// 0: "irc",
	// 0: "jtag",
	// 0: "iscp",
	// 0: "mediad",
	// 0: "dusk",
	// 0: "napster",
	// 0: "encase",
	// 0: "moo",
	// 0: "asf-rmcp",
	// 0: "drda",
	// 0: "nat-pmp",
	// 0: "avk",
	// 0: "websocket",
	// 0: "wub-command",
	// 0: "caigos-conspectus",
	// 0: "fw1-secureremote",
	// 0: "squeezecli",
	// 0: "omp",
	// 0: "lucent-fwadm",
	// 0: "netdevil",
	// 0: "icy",
	// 0: "rtp",
	// 0: "maxdb",
	// 0: "oracle",
	// 0: "appguard-db",
	// 0: "minecraft-socketapi",
	// 0: "halfd",
	// 0: "ibm-mqseries",
	// 0: "ovhcheckout",
	// 0: "wsman",
	// 0: "rfactor-monitor",
	// 0: "bruker-axs",
	// 0: "wbem",
	// 0: "audioworks",
	// 0: "rpd",
	// 0: "jxta",
	// 0: "niprint",
	// 0: "pmcd",
	// 0: "groupwise",
	// 0: "consul",
	// 0: "spice",
	// 0: "kismet",
	// 0: "fw1-pslogon",
	// 0: "terraria",
	// 0: "cvspserver",
	// 0: "msrpc",
	// 0: "starbound",
	// 0: "sstp",
	// 0: "netradio",
	// 0: "remote-rac",
	// 0: "geovision-control",
	// 0: "pbs-maui",
	// 0: "filenet-pch",
	// 0: "tibia",
	// 0: "fastcgi",
	// 0: "dec-notes",
	// 0: "gms",
	// 0: "mudnames",
	// 0: "cso",
	// 0: "airport-admin",
	// 0: "intersys-cache",
	// 0: "ipremote",
	// 0: "traficon-flux",
	// 0: "icecream",
	// 0: "intertel-ctl",
	// 0: "ndv",
	// 0: "ixia",
	// 0: "srcds",
	// 0: "cryptonote",
	// 0: "riverbed-stats",
	// 0: "echo",
	// 0: "rpacd",
	// 0: "trackerlink",
	// 0: "automate",
	// 0: "exec",
	// 0: "kazaa-http",
	// 0: "pop3",
	// 0: "sharefolder",
	// 0: "jabber",
	// 0: "beep",
	// 0: "ph-addressbook",
	// 0: "caigos-fundus",
	// 0: "eggdrop",
	// 0: "pcmeasure",
	// 0: "pop2",
	// 0: "bitkeeper",
	// 0: "perfd",
	// 0: "rcon",
	// 0: "ptcp",
	// 0: "exalead",
	// 0: "spotify-login",
	// 0: "scifinder",
	// 0: "routeros-api",
	// 0: "issc",
	// 0: "monetdb-ctl",
	// 0: "netsupport",
	// 0: "nbd",
	// 0: "avaya-aom",
	// 0: "moneyworks",
	// 0: "shoutcast",
	// 0: "rtdscchcch",
	// 0: "jute",
	// 0: "kismet-drone",
	// 0: "runes-of-magic",
	// 0: "togamelogin",
	// 0: "gearman",
	// 0: "file-replication",
	// 0: "teamspeak-tcpquery",
	// 0: "pcp",
	// 0: "raop",
	// 0: "arcserve",
	// 0: "docbroker",
	// 0: "wins",
	// 0: "acmp",
	// 0: "fw1-topology",
	// 0: "seagull-lm",
	// 0: "bluecoat-logd",
	// 0: "spark",
	// 0: "4d-server",
	// 0: "resvc",
	// 0: "amqp",
	// 0: "unreal-media",
	// 0: "nuttcp",
	// 0: "networkaudio",
	// 0: "smpp",
	// 0: "hazelcast",
	// 0: "arkstats",
	// 0: "munin",
	// 0: "gntp",
	// 0: "lscp",
	// 0: "dict",
	// 0: "jsonrpc",
	// 0: "quake3",
	// 0: "g15daemon",
	// 0: "openlookup",
	// 0: "video",
	// 0: "ts3",
	// 0: "printer",
	// 0: "stingray",
	// 0: "wms",
	// 0: "bittorrent-udp-tracker",
	// 0: "speechd",
	// 0: "g6-remote",
	// 0: "hpiod",
	// 0: "junoscript",
	// 0: "codeforge",
	// 0: "bigant",
	// 0: "msdtc",
	// 0: "dtls",
	// 0: "sybaseanywhere",
	// 0: "adabas-d",
	// 0: "pyro",
	// 0: "nsclient",
	// 0: "digifort",
	// 0: "metasploit",
	// 0: "servicetags",
	// 0: "wyse-devmgr",
	// 0: "cmae",
	// 0: "gamebots-control",
	// 0: "meetingmaker",
	// 0: "nmea-0183",
	// 0: "patrol",
	// 0: "avg",
	// 0: "ibm-hmc",
	// 0: "imap-proxy",
	// 0: "lexlm",
	// 0: "cvsup",
	// 0: "para-ups",
	// 0: "ssl/vmware-auth",
	// 0: "conserver",
	// 0: "multicraft",
	// 0: "xns",
	// 0: "mobilemouse",
	// 0: "goldengate",
	// 0: "fsd",
	// 0: "ipcam",
	// 0: "tmail",
	// 0: "ossec-agent",
	// 0: "echolink",
	// 0: "tinyfw",
	// 0: "elm-agent",
	// 0: "jetdirect",
	// 0: "pmud",
	// 0: "anyremote",
	// 0: "openfpc",
	// 0: "mosmig",
	// 0: "svnserve",
	// 0: "intow",
	// 0: "istat",
	// 0: "chat",
	// 0: "envisalink",
	// 0: "ixia-unknown",
	// 0: "kshell",
	// 0: "slingbox",
	// 0: "pso-login",
	// 0: "trasker",
	// 0: "etrayz-setup",
	// 0: "mrtgext-nlm",
	// 0: "serversettingsd",
	// 0: "acti-control",
	// 0: "digifort-lpr",
	// 0: "galaxy",
	// 0: "java-object",
	// 0: "realport",
	// 0: "spy-net",
	// 0: "utrmcd",
	// 0: "quake",
	// 0: "clsbd",
	// 0: "jenkins-listener",
	// 0: "ncat-chat",
	// 0: "as2",
	// 0: "tftp",
	// 0: "freenet",
	// 0: "hp-radia",
	// 0: "durian",
	// 0: "trackmania-gbx",
	// 0: "samsung-twain",
	// 0: "ssh",
	// 0: "net-rpc",
	// 0: "webmin",
	// 0: "statd",
	// 0: "nnsrv",
	// 0: "citynet",
	// 0: "quagga",
	// 0: "samsung-sap",
	// 0: "control-gc-ports",
	// 0: "loadrunner-vts",
	// 0: "citrix-ima",
	// 0: "nrpep",
	// 0: "papouch-tme",
	// 0: "shivahose",
	// 0: "lsf-mbd",
	// 0: "autosys",
	// 0: "freedoko",
	// 0: "systat",
	// 0: "minisql",
	// 0: "netman",
	// 0: "caigos-pactor",
	// 0: "omniback",
	// 0: "fhem",
	// 0: "http-ocsp",
	// 0: "omapi",
	// 0: "backupexec-remote",
	// 0: "sopcast",
	// 0: "netsync",
	// 0: "synchroedit",
	// 0: "sharp-twain",
	// 0: "rconj",
	// 0: "tsdns",
	// 0: "oem-agent",
	// 0: "nameserver",
	// 0: "pbx-alarm",
	// 0: "caigos-paratus",
	// 0: "cyrus-sync",
	// 0: "vhcs",
	// 0: "osiris",
	// 0: "routersetup",
	// 0: "hp-pjl",
	// 0: "conference",
	// 0: "xplorer",
	// 0: "sourceviewerserver",
	// 0: "dcc",
	// 0: "cmrcservice",
	// 0: "sap-logviewer",
	// 0: "securepath",
	// 0: "myproxy",
	// 0: "nsunicast",
	// 0: "trendnet-webcam",
	// 0: "urbackup",
	// 0: "freeciv",
	// 0: "beidpcscd",
	// 0: "bro",
	// 0: "nping-echo",
	// 0: "sunscreen-adm",
	// 0: "ssc-agent",
	// 0: "opsec-ufp",
	// 0: "ms-sql-m",
	// 0: "partimage",
	// 0: "openvpn",
	// 0: "zeo",
	// 0: "taxinav",
	// 0: "go-login",
	// 0: "itach",
	// 0: "pcs-partner",
	// 0: "virtualgl",
	// 0: "ipfs",
	// 0: "rfbuoy",
	// 0: "saprouter",
	// 0: "minecraft-classic",
	// 0: "mc-nmf",
	// 0: "xtel",
	// 0: "ouman-trend",
	// 0: "policy",
	// 0: "isakmp",
	// 0: "siemens-logo",
	// 0: "drweb",
	// 0: "pcmiler",
	// 0: "rtsp",
	// 0: "achat",
	// 0: "citrix-licensing",
	// 0: "ssl/consul-rpc",
	// 0: "netsupport-dna",
	// 0: "qsp-proxy",
	// 0: "solproxy",
	// 0: "redcarpet",
	// 0: "sap-its",
	// 0: "thinprint",
	// 0: "firebird",
	// 0: "barracuda-dcagent",
	// 0: "libp2p-multistream",
	// 0: "renderer",
	// 0: "git",
	// 0: "couchbase-tap",
	// 0: "calibre-json",
	// 0: "timeedit",
	// 0: "rsa-authmgr",
	// 0: "service-monitor",
	// 0: "digi-usb",
	// 0: "sip-proxy",
	// 0: "mdns",
	// 0: "zookeeper",
	// 0: "qmqp",
	// 0: "ntrip",
	// 0: "fw1-log",
	// 0: "vtun",
	// 0: "teamtalk",
	// 0: "openvpn-management",
	// 0: "mupdate",
	// 0: "soldat",
	// 0: "stratum",
	// 0: "oftp",
	// 0: "stargazer",
	// 0: "iodine",
	// 0: "wtam",
	// 0: "storagecraft-image",
	// 0: "commvault",
	// 0: "fortinet-sso",
	// 0: "drb",
	// 0: "hue-link",
	// 0: "osu-nms",
	// 0: "winshell",
	// 0: "spectraport",
	// 0: "symantec-av",
	// 0: "pjlink",
	// 0: "qemu-vlan",
	// 0: "vidyoroom",
	// 0: "mydoom",
	// 0: "ncd-diag",
	// 0: "quasar",
	// 0: "ajp13",
	// 0: "psql-btrieve",
	// 0: "pathfinder-xml",
	// 0: "xmpp",
	// 0: "X11",
	// 0: "fw1-rlogin",
	// 0: "elm-manager",
	// 0: "ndb_mgmd",
	// 0: "acarsd",
	// 0: "chargen",
	// 0: "drac-console",
	// 0: "rhpp",
	// 0: "caicci",
	// 0: "tsd",
	// 0: "talk",
	// 0: "afp",
	// 0: "genetec-5400",
	// 0: "rds",
	// 0: "goverlan",
	// 0: "keriopfgui",
	// 0: "rfidquery",
	// 0: "outpost-ctl",
	// 0: "pso-gate",
	// 0: "sonork",
	// 0: "rhapsody",
	// 0: "t-doc-2000",
	// 0: "ssl/http",
	// 0: "crestron-ctp",
	// 0: "drobo-dsvc",
	// 0: "keepnote",
	// 0: "opentable",
	// 0: "bmc-perform-service",
	// 0: "ftp-proxy",
	// 0: "hylafax",
	// 0: "keyence-pc",
	// 0: "ncid",
	// 0: "scmm",
	// 0: "zmodem",
	// 0: "ripbot",
	// 0: "apollo-server",
	// 0: "clementine",
	// 0: "directconnect-admin",

	// 0: "pcworx",
	// 0: "mohaa-gamespy",
	// 0: "activefax",
	// 0: "distccd",
	// 0: "mas-financial",
	// 0: "vuze-dht",
	// 0: "cddbp",
	// 0: "virtualhere",
	// 0: "upsd",
	// 0: "sourceoffice",
	// 0: "xfce-session",
	// 0: "csta",
	// 0: "mp-automation",
	// 0: "rse",
	// 0: "kguard",
	// 0: "monopd",
	// 0: "rationalsoft",
	// 0: "apple-sasl",
	// 0: "diablo2",
	// 0: "openttd",
	// 0: "sentinel-lm",
	// 0: "niagara-fox",
	// 0: "gnatbox",
	// 0: "zenius-sms",
	// 0: "h.239",

	// 0: "ssl/sophos",
	// 0: "softplc",
	// 0: "frozen-bubble",
	// 0: "pharos",
	// 0: "stageremote",
	// 0: "prelude-manager",
	// 0: "rgpsp",
	// 0: "mail-admin",
	// 0: "csync",
	// 0: "geovision-audio",
	// 0: "devonthink",
	// 0: "egosecure-xmlrpc",
	// 0: "geovision-mobile",
	// 0: "bittorrent-utp",
	// 0: "timbuktu",
	// 0: "h2",
	// 0: "arucer",
	// 0: "emc-datadomain",
	// 0: "irods",
	// 0: "afs3-fileserver",
	// 0: "netbios-ns",
	// 0: "ptp-ip",
	// 0: "olsrd-txtinfo",
	// 0: "univention-json",
	// 0: "pgpool",
	// 0: "sarad",

	// 0: "dnsix",
	// 0: "spmd",
	// 0: "xine-remote",
	// 0: "gopro-json",
	// 0: "hp-logic-analyzer",
	// 0: "metasploit-msgrpc",
	// 0: "jrpgt",
	// 0: "mmouse",
	// 0: "pc-monitor",
	// 0: "ttscp",
	// 0: "minebuilder",
	// 0: "warcraft",
	// 0: "isymphony-status",
	// 0: "zenimaging",
	// 0: "telnet-proxy",
	// 0: "lotusnotes",
	// 0: "OpenSSH",
	// 0: "ir-alerts",
	// 0: "lisa",
	// 0: "unreal",
	// 0: "silc",
	// 0: "kumo-manager",
	// 0: "genetec-directory",
	// 0: "hpssd",
	// 0: "am-pdp",
	// 0: "ormi",
	// 0: "powerchute",
	// 0: "darkcomet",
	// 0: "stockfish",
	// 0: "tn3270",
	// 0: "gadu",
	// 0: "dragon",
	// 0: "landesk",
	// 0: "ciscopsdm",
	// 0: "caigos-conductus",
	// 0: "giop",
	// 0: "bnetd",
	// 0: "motorola-devmgr",
	// 0: "python-mp",
	// 0: "3cx-tunnel",
	// 0: "printer-json",
	// 0: "millennium-ils",
	// 0: "roku",
	// 0: "mxie",
	// 0: "xamarin",
	// 0: "zabbix",
	// 0: "brassmonkey",
	// 0: "lorex-monitor",
	// 0: "symantec-esm",
	// 0: "http-proxy-ctrl",
	// 0: "lineage-ii",
	// 0: "venti",
	// 0: "imond",
	// 0: "ssl/steam",
	// 0: "upnp",
	// 0: "watchguard",
	// 0: "cisco7200sim",
	// 0: "hadoop-ipc",
	// 0: "dvr-video",
	// 0: "exacqvision",
	// 0: "misys-loaniq",
	// 0: "nomachine-nx",
	// 0: "trillian",
	// 0: "realplayfavs",
	// 0: "rifa-dvr",
	// 0: "labtech-redirector",
	// 0: "uc4",
	// 0: "tor",
	// 0: "scmbug",
	// 0: "maplestory",
	// 0: "razor2",
	// 0: "telemecanique",
	// 0: "ssdp",
	// 0: "audit",
	// 0: "ipmi-usb",
	// 0: "serial",
	// 0: "authpoint",
	// 0: "rethinkdb-client",
	// 0: "socks5",
	// 0: "ericssontimestep",
	// 0: "webster",
	// 0: "vertica",
	// 0: "teamspeak2",
	// 0: "digifort-analytics",
	// 0: "signiant",
	// 0: "mep",
	// 0: "ca-unicenter",
	// 0: "musicvr",
	// 0: "p4d",
	// 0: "qaweb",
	// 0: "clam",
	// 0: "genetec-5500",
	// 0: "instrument-manager",
	// 0: "mentorbs",
	// 0: "domaintime",
	// 0: "postx-reporting",
	// 0: "ncacn_http",
	// 0: "sun-alom",
	// 0: "bitdefender-ctrl",
	// 0: "omniinet",
	// 0: "obiee",
	// 0: "securetransport",
	// 0: "shaiya",
	// 0: "vmware-aam",
	// 0: "websm",
	// 0: "hp-problemdiagnostics",
	// 0: "psql",
	// 0: "netassistant",
	// 0: "aastra-pbx",
	// 0: "adobe-crossdomain",
	// 0: "datamaxdb",
	// 0: "ms-wbt-server-proxy",
	// 0: "nntp",
	// 0: "qds",
	// 0: "utsvc",
	// 0: "tivo-remote",
	// 0: "elasticsearch",
	// 0: "dbsnmp",
	// 0: "wolfssl",
	// 0: "megafillers",
	// 0: "hp-gsg",
	// 0: "slx",
	// 0: "yiff",
	// 0: "maas-rpc",
	// 0: "mud",
	// 0: "extron-serial",
	// 0: "acpc",
	// 0: "ssl/openvas",
	// 0: "crossfire",
	// 0: "damewaremr",
	// 0: "ice",
	// 0: "squeezecenter",
	// 0: "solfe",
	// 0: "minecraft-pe",
	// 0: "fiesta-online",
	// 0: "quest_launcher",
	// 0: "ircbot",
	// 0: "aleph",
	// 0: "vulnserver",
	// 0: "hl7-mlp",
	// 0: "pi-hole-stats",
	// 0: "afsmain",
	// 0: "paloalto-agent",
	// 0: "wingate",
	// 0: "icontrolav2",
	// 0: "uptime-agent",
	// 0: "gpsd",
	// 0: "ovs-agent",
	// 0: "rtsp-proxy",
	// 0: "fyre",
	// 0: "mpd",
	// 0: "bittorrent-tracker",
	// 0: "emc-pp-mgmtsvc",
	// 0: "cisco-sla-responder",
	// 0: "rethinkdb-intracluster",
	// 0: "spideroak",
	// 0: "synergy",
	// 0: "gipc",
	// 0: "dslcpe",
	// 0: "informix",
	// 0: "bindshell",
	// 0: "paromed",
	// 0: "econtagt",
	// 0: "xmpp-transport",
	// 0: "xmlsysd",
	// 0: "bgp",
	// 0: "isymphony-cli",
	// 0: "scalix-ual",
	// 0: "zebedee",
	// 0: "sybase-adaptive",
	// 0: "as-signon",
	// 0: "telematics",
	// 0: "netasq-admin",

	// 0: "boinc",
	// 0: "memcached",
	// 0: "utsessiond",
	// 0: "arkeia",
	// 0: "socks-proxy",
	// 0: "sphinx-search",
	// 0: "allseeingeye",
	// 0: "cops",
	// 0: "rowmote",
	// 0: "postgresql",
	// 0: "polycom-mgc",
	// 0: "splashtop",
	// 0: "imaze-game",
	// 0: "mqtt",
	// 0: "chess",
	// 0: "gnats",
	// 0: "goldsync",
	// 0: "compuware-lm",
	// 0: "time",
	// 0: "metatrader",
	// 0: "docker-swarm",
	// 0: "firewall",
	// 0: "netsoul",
	// 0: "hasp-lm",
	// 0: "afarianotify",
	// 0: "POP3",
	// 0: "1c-server",
	// 0: "digital-sprite-status",
	// 0: "stomp",
	// 0: "ipp",
	// 0: "erlang-node",
	// 0: "activesync",
	// 0: "slnp",
	// 0: "medcart",
	// 0: "airmedia-audio",
	// 0: "rsa-appliance",
	// 0: "gnutella",
	// 0: "sand-db",
	// 0: "remote-volume",
	// 0: "gkrellm",
	// 0: "litecoin-jsonrpc",
	// 0: "vtp",
	// 0: "tor-control",
	// 0: "exportfs",
	// 0: "ncp",
	// 0: "castv2",
	// 0: "cirrato-client",
	// 0: "dynast-solver",
	// 0: "domain",
	// 0: "sdcomm",
	// 0: "vizio-tv",
	// 0: "hillstone-vpn",
	// 0: "apcupsd",
	// 0: "doka5",
	// 0: "eftserv",
	// 0: "electra",
	// 0: "vss",
	// 0: "kerberos",
	// 0: "secure-socket",
	// 0: "burk-autopilot",
	// 0: "freeswitch-event",
	// 0: "tdm",
	// 0: "portlistener",
	// 0: "zmtp",
	// 0: "flashconnect",
	// 0: "pbs",
	// 0: "opinionsquare",
	// 0: "app",
	// 0: "drobo-nasd",
	// 0: "lanforge",
	// 0: "nje",
	// 0: "articy-server",
	// 0: "nightwatchman",
	// 0: "bacnet",
	// 0: "logpad",
	// 0: "wincor-atm",
	// 0: "utorrent-udp",
	// 0: "qtopia-transfer",
	// 0: "RemoteMouse",
	// 0: "zend-java-bridge",
	// 0: "hddtemp",
	// 0: "monetdb",
	// 0: "ms-wbt-server",
	// 0: "gpsd-ng",
	// 0: "ets2",
	// 0: "decomsrv",
	// 0: "yamaha-comm",
	// 0: "proconos",
	// 0: "banner-ivu",
	// 0: "caldav",
	// 0: "wrproxy",

	// 0: "daap",
	// 0: "hbase",
	// 0: "dominoconsole",
	// 0: "tarantool",
	// 0: "artsd",
	// 0: "novastor-backup",
	// 0: "righteous-backup",
	// 0: "computone-intelliserver",
	// 0: "loglogic",
	// 0: "font-service",
	// 0: "asterisk-proxy",
	// 0: "lmtp",
	// 0: "hama-radio",
	// 0: "fsae",
	// 0: "priv-print",
	// 0: "afs",
	// 0: "optommp",
	// 0: "wow",
	// 0: "srvloc",
	// 0: "directfb",
	// 0: "bas",
	// 0: "check_mk",
	// 0: "vmware-auth",
	// 0: "bprd",
	// 0: "access-remote-pc",
	// 0: "bacula-sd",
	// 0: "irr",
	// 0: "ingrian-xml",
	// 0: "ccnet",
	// 0: "vnc-http",
	// 0: "pot",
	// 0: "jd-gui",
	// 0: "oracle-mts",
	// 0: "sguil",

	// 0: "quake2",
	// 0: "efi-workstation",
	// 0: "gopher",
	// 0: "pioneers-meta",
	// 0: "tuxedo-wsl",
	// 0: "jmon",

	// 0: "asus-nfc",
	// 0: "buildservice",
	// 0: "lanrev-agent",
	// 0: "rpcbind",
	// 0: "slp-srvreg",
	// 0: "aperio-aaf",
	// 0: "pksd",
	// 0: "monsoon",
	// 0: "imsp",
	// 0: "nngs",

	// 0: "talesofpirates-gate",
	// 0: "sdlog",
	// 0: "sftp",
	// 0: "sma-solar",
	// 0: "smtp-stats",
	// 0: "netapp-filer",
	// 0: "tandem-print",
	// 0: "bentley-projectwise",
	// 0: "ed2klink",
	// 0: "adabas",
	// 0: "resin-watchdog",
	// 0: "ksystemguard",
	// 0: "pop3pw",
	// 0: "mon",
	// 0: "zenworks",
	// 0: "emco-remote-screenshot",
	// 0: "winagents-hyperconf",
	// 0: "rexec",
	// 0: "rmate",
	// 0: "wifi-mouse",
	// 0: "lantronix-config",
	// 0: "siebel",
	// 0: "libvirt-rpc",
	// 0: "aplus",
	// 0: "ca-mq",
	// 0: "biff",
	// 0: "hama-radio2",
	// 0: "sonicmq",
	// 0: "bacula-fd",
	// 0: "saft",
	// 0: "clickhouse",
	// 0: "tgcmd",
	// 0: "arcserve-gdd",
	// 0: "filezilla",
	// 0: "irc-proxy",
	// 0: "pioneers",
	// 0: "srun",
	// 0: "netusb",
	// 0: "printer-admin",
	// 0: "linuxconf",
	// 0: "drawpile",
	// 0: "palace",
	// 0: "pgas",
	// 0: "bmc-tmart",
	// 0: "jdbc",
	// 0: "softros-im",
	// 0: "speech",
	// 0: "tinc",
	// 0: "rlm",
	// 0: "mogilefs",
	// 0: "rotctld",
	// 0: "ccirmtd",

	// 0: "gd-comm",
	// 0: "slurm",
	// 0: "insteon-plm",
	// 0: "cccam",
	// 0: "sphereicall",
	// 0: "dnastar",
	// 0: "softwarepatrol",
	// 0: "megaraid-monitor",
	// 0: "java-rmi",
	// 0: "oo-defrag",
	// 0: "tng-dts",

	// 0: "vdr",
	// 0: "http-proxy",
	// 0: "lns",
	// 0: "textui",
	// 0: "xmail-ctrl",
	// 0: "xml-print",
	// 0: "zeo-monitor",
	// 0: "ntop-http",
	// 0: "msn",
	// 0: "antivir",
	// 0: "iss-realsecure",
	// 0: "mwti-rpc",
	// 0: "hptsvr",
	// 0: "unknown",
	// 0: "xbmsp",
	// 0: "pppctl",
	// 0: "remote-control",
	// 0: "altiris-agent",
	// 0: "freevcs",
	// 0: "ganglia",
	// 0: "remoteanything",
	// 0: "tcpwrapped",
	// 0: "guildwars2-heartbeat",
	// 0: "netbackup-bpdbm",
	// 0: "prisontale",
}
