export {
  api,
  createApi,
  getBackendUrl,
  formatBytes,
  formatTimestamp,
  formatDuration,
} from './api';

export type { NetcapApiClient } from './api';

export { highlightFilterExpression } from './filterSyntaxHighlight';
export type { FilterToken } from './filterSyntaxHighlight';

export { highlightBPFExpression } from './bpfSyntaxHighlight';
export type { BPFToken } from './bpfSyntaxHighlight';

export { highlightRegexPattern } from './regexSyntaxHighlight';
export type { RegexToken } from './regexSyntaxHighlight';

export type {
  // Response types
  ProcessingStats,
  FileError,
  StatsResponse,
  AuditStatsResponse,
  StatusResponse,
  UploadResponse,
  QuotaResponse,
  FileInfo,
  AuditFileInfo,
  AuditMetadata,
  ExtractedFileInfo,
  ExtractedFilesResponse,
  VersionInfo,
  DatabaseInfo,
  DBFileInfo,
  DPIInfo,
  UserDPIPreferences,
  ConfigOption,
  ConfigResponse,
  DecoderInfo,
  DecodersResponse,
  DecoderConfig,
  DecoderConfigFile,
  DecoderFieldsResponse,
  AllDecoderFieldsResponse,
  HarvesterInfo,
  HarvestersResponse,
  HarvestersConfig,
  HarvesterConfigItem,
  CustomHarvesterConfig,
  HarvesterPresetInfo,
  HarvesterPresetListResponse,
  ServiceProbeInfo,
  ServiceProbesResponse,
  TestProbeRequest,
  TestProbeResponse,
  NetworkInterfaceInfo,
  BPFExample,
  BPFInfoResponse,
  BPFConfig,
  SystemInfo,
  ChartDataPoint,
  ChartDataResponse,
  ChartFieldInfo,
  ChartFieldsResponse,
  ProtocolStats,
  SankeyLink,
  ProtocolHierarchyResponse,
  ReportIssueRequest,
  ReportIssueResponse,
  Rule,
  ResponseAction,
  RulesResponse,
  CreateRuleRequest,
  UpdateRuleRequest,
  RuleSet,
  RuleSetsResponse,
  UpdateRuleSetRequest,
  Alert,
  AlertsResponse,
  GroupedAlert,
  GroupedAlertsResponse,
  AlertStatsResponse,
  FieldInfo,
  FieldsResponse,
  FieldValuesResponse,
  InjectionRule,
  InjectionRulesResponse,
  CreateInjectionRuleRequest,
  UpdateInjectionRuleRequest,
  InjectionEvent,
  InjectionEventsResponse,
  InjectionStatsResponse,
  InjectionAction,
  InjectionActionConfig,
  ConversationData,
  ErrorLogInfo,
  AggregatedError,
  SessionStatus,
  ProgressInfo,
  TrySession,
} from './api';
