/*
 * NETCAP - Traffic Analysis Framework
 * Copyright (c) 2017-2020 Philipp Mieden <dreadl0ck [at] protonmail [dot] ch>
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package rules

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/expr-lang/expr/vm"
	"gopkg.in/yaml.v2"

	"github.com/dreadl0ck/netcap/filter"
	"github.com/dreadl0ck/netcap/types"
)

// Rule represents a detection rule that can be evaluated against audit records.
type Rule struct {
	// Name is a unique identifier for the rule
	Name string `yaml:"name"`

	// Description provides human-readable information about the rule
	Description string `yaml:"description"`

	// Type specifies which audit record type this rule applies to (e.g., "TCP", "HTTP")
	Type string `yaml:"type"`

	// Expression is the expr-lang expression to evaluate
	Expression string `yaml:"expression"`

	// Severity indicates the importance of alerts generated by this rule
	// Valid values: low, medium, high, critical
	Severity string `yaml:"severity"`

	// MITRE contains MITRE ATT&CK technique IDs associated with this rule
	MITRE []string `yaml:"mitre"`

	// Tags are custom labels for categorizing rules
	Tags []string `yaml:"tags"`

	// Enabled determines whether this rule is active
	Enabled bool `yaml:"enabled"`

	// Threshold is the number of times this rule must match before triggering an alert
	// If 0 or 1, alert is triggered immediately on first match (default behavior)
	Threshold int `yaml:"threshold,omitempty"`

	// ThresholdWindow is the time window (in seconds) within which the threshold must be reached
	// Only applicable when Threshold > 1. Default is 60 seconds (1 minute)
	ThresholdWindow int `yaml:"threshold_window,omitempty"`

	// compiled is the compiled expression program (not serialized)
	compiled *vm.Program
}

// Config holds a collection of rules loaded from a YAML file.
type Config struct {
	Description string  `yaml:"description"`
	Rules       []*Rule `yaml:"rules"`
}

// LoadRulesFromFile loads rules from a YAML file.
func LoadRulesFromFile(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read rules file: %w", err)
	}

	var config Config
	err = yaml.Unmarshal(data, &config)
	if err != nil {
		return nil, fmt.Errorf("failed to parse rules YAML: %w", err)
	}

	return &config, nil
}

// CompileRules compiles all rule expressions in the configuration.
func CompileRules(config *Config) error {
	for i, rule := range config.Rules {
		if !rule.Enabled {
			continue
		}

		if rule.Expression == "" {
			return fmt.Errorf("rule %s has empty expression", rule.Name)
		}

		// Convert type string to types.Type
		recordType, err := parseRecordType(rule.Type)
		if err != nil {
			return fmt.Errorf("rule %s: %w", rule.Name, err)
		}

		// Compile the expression
		program, err := filter.CompileExpression(rule.Expression, recordType)
		if err != nil {
			return fmt.Errorf("failed to compile rule %s: %w", rule.Name, err)
		}

		config.Rules[i].compiled = program
	}

	return nil
}

// EvaluateRule evaluates a rule against an audit record and returns an alert if it matches.
func EvaluateRule(rule *Rule, record types.AuditRecord) (*types.Alert, error) {
	if !rule.Enabled {
		return nil, nil
	}

	if rule.compiled == nil {
		return nil, fmt.Errorf("rule %s is not compiled", rule.Name)
	}

	// Evaluate the expression
	match, err := filter.EvaluateExpression(rule.compiled, record)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate rule %s: %w", rule.Name, err)
	}

	if !match {
		return nil, nil
	}

	// Ensure tags is never nil (use empty slice if nil)
	tags := rule.Tags
	if tags == nil {
		tags = []string{}
	}

	// Create alert
	alert := &types.Alert{
		Timestamp:      time.Now().UnixNano(),
		Name:           rule.Name,
		Description:    rule.Description,
		RuleName:       rule.Name,
		RecordType:     record.NetcapType().String(),
		Severity:       rule.Severity,
		Tags:           tags,
		RuleExpression: rule.Expression,
		Threshold:      int32(rule.Threshold),
		ThresholdWindow: int32(rule.ThresholdWindow),
	}

	// Set MITRE ATT&CK IDs (join multiple IDs)
	if len(rule.MITRE) > 0 {
		alert.MITRE = strings.Join(rule.MITRE, ",")
	}

	// Extract source and destination from record
	alert.SrcIP = record.Src()
	alert.DstIP = record.Dst()

	// Try to marshal the record as JSON for context
	recordJSON, err := json.Marshal(record)
	if err == nil {
		alert.MatchedRecord = string(recordJSON)
	}

	return alert, nil
}

// parseRecordType converts a type string (e.g., "TCP", "HTTP") to types.Type.
func parseRecordType(typeStr string) (types.Type, error) {
	// Add NC_ prefix if not present
	if !strings.HasPrefix(typeStr, "NC_") {
		typeStr = "NC_" + typeStr
	}

	// Look up the type value
	typeValue, ok := types.Type_value[typeStr]
	if !ok {
		return 0, fmt.Errorf("unknown record type: %s", typeStr)
	}

	return types.Type(typeValue), nil
}

// ValidateSeverity checks if a severity string is valid.
func ValidateSeverity(severity string) bool {
	switch strings.ToLower(severity) {
	case "low", "medium", "high", "critical":
		return true
	default:
		return false
	}
}
