/*
 * NETCAP - Traffic Analysis Framework
 * Copyright (c) Philipp Mieden <dreadl0ck [at] protonmail [dot] ch>
 * License: GNU General Public License v3.0
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package rules

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/expr-lang/expr/vm"
	"gopkg.in/yaml.v2"

	"github.com/dreadl0ck/netcap/internal/filter"
	"github.com/dreadl0ck/netcap/types"
)

// Rule represents a detection rule that can be evaluated against audit records.
type Rule struct {
	// Name is a unique identifier for the rule
	Name string `yaml:"name"`

	// Description provides human-readable information about the rule
	Description string `yaml:"description"`

	// Type specifies which audit record type this rule applies to (e.g., "TCP", "HTTP")
	Type string `yaml:"type"`

	// Expression is the expr-lang expression to evaluate
	Expression string `yaml:"expression"`

	// Severity indicates the importance of alerts generated by this rule
	// Valid values: low, medium, high, critical
	Severity string `yaml:"severity"`

	// MITRE contains MITRE ATT&CK technique IDs associated with this rule
	MITRE []string `yaml:"mitre"`

	// Tags are custom labels for categorizing rules
	Tags []string `yaml:"tags"`

	// Enabled determines whether this rule is active
	Enabled bool `yaml:"enabled"`

	// Threshold is the number of times this rule must match before triggering an alert
	// If 0 or 1, alert is triggered immediately on first match (default behavior)
	Threshold int `yaml:"threshold,omitempty"`

	// ThresholdWindow is the time window (in seconds) within which the threshold must be reached
	// Only applicable when Threshold > 1. Default is 60 seconds (1 minute)
	ThresholdWindow int `yaml:"threshold_window,omitempty"`

	// Actions are response actions to execute when this rule matches and generates an alert.
	// These are automated responses like blocking IPs via iptables.
	Actions []*ResponseAction `yaml:"actions,omitempty"`

	// compiled is the compiled expression program (not serialized)
	compiled *vm.Program
}

// ResponseAction defines an automated response to a rule match.
type ResponseAction struct {
	// Type is the action type (iptables_block, iptables_reject, iptables_rate_limit, iptables_log)
	Type string `yaml:"type"`

	// Config contains action-specific configuration
	Config map[string]any `yaml:"config,omitempty"`

	// Enabled allows disabling specific actions (default: true if omitted)
	Enabled *bool `yaml:"enabled,omitempty"`
}

// IsEnabled returns true if the action is enabled (default is true).
func (a *ResponseAction) IsEnabled() bool {
	if a.Enabled == nil {
		return true // Default to enabled
	}
	return *a.Enabled
}

// Validate checks if the response action has a valid type.
func (a *ResponseAction) Validate() error {
	switch a.Type {
	case "iptables_block", "iptables_reject", "iptables_rate_limit", "iptables_log":
		return nil
	default:
		return fmt.Errorf("unknown response action type: %s", a.Type)
	}
}

// Config holds a collection of rules loaded from a YAML file.
type Config struct {
	Description string  `yaml:"description"`
	Rules       []*Rule `yaml:"rules"`
}

// LoadRulesFromFile loads rules from a YAML file.
func LoadRulesFromFile(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read rules file: %w", err)
	}

	var config Config
	err = yaml.Unmarshal(data, &config)
	if err != nil {
		return nil, fmt.Errorf("failed to parse rules YAML: %w", err)
	}

	return &config, nil
}

// LoadRulesFromDirectory loads all rule files from a directory and returns a merged configuration.
func LoadRulesFromDirectory(dirPath string) (*Config, error) {
	config := &Config{
		Rules: []*Rule{},
	}

	entries, err := os.ReadDir(dirPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read rules directory: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".yml") {
			continue
		}

		filePath := filepath.Join(dirPath, entry.Name())
		fileConfig, err := LoadRulesFromFile(filePath)
		if err != nil {
			return nil, fmt.Errorf("failed to load rules from %s: %w", entry.Name(), err)
		}

		config.Rules = append(config.Rules, fileConfig.Rules...)
	}

	return config, nil
}

// CompileRules compiles all rule expressions in the configuration.
func CompileRules(config *Config) error {
	for i, rule := range config.Rules {
		if !rule.Enabled {
			continue
		}

		if rule.Expression == "" {
			return fmt.Errorf("rule %s has empty expression", rule.Name)
		}

		// Convert type string to types.Type
		recordType, err := parseRecordType(rule.Type)
		if err != nil {
			return fmt.Errorf("rule %s: %w", rule.Name, err)
		}

		// Compile the expression
		program, err := filter.CompileExpression(rule.Expression, recordType)
		if err != nil {
			return fmt.Errorf("failed to compile rule %s: %w", rule.Name, err)
		}

		config.Rules[i].compiled = program
	}

	return nil
}

// EvaluateRule evaluates a rule against an audit record and returns an alert if it matches.
func EvaluateRule(rule *Rule, record types.AuditRecord) (*types.Alert, error) {
	if !rule.Enabled {
		return nil, nil
	}

	if rule.compiled == nil {
		return nil, fmt.Errorf("rule %s is not compiled", rule.Name)
	}

	// Evaluate the expression
	match, err := filter.EvaluateExpression(rule.compiled, record)
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate rule %s: %w", rule.Name, err)
	}

	if !match {
		return nil, nil
	}

	// Ensure tags is never nil (use empty slice if nil)
	tags := rule.Tags
	if tags == nil {
		tags = []string{}
	}

	// Create alert
	alert := &types.Alert{
		Timestamp:       time.Now().UnixNano(),
		Name:            rule.Name,
		Description:     rule.Description,
		RuleName:        rule.Name,
		RecordType:      record.NetcapType().String(),
		Severity:        rule.Severity,
		Tags:            tags,
		RuleExpression:  rule.Expression,
		Threshold:       int32(rule.Threshold),
		ThresholdWindow: int32(rule.ThresholdWindow),
	}

	// Set MITRE ATT&CK IDs (join multiple IDs)
	if len(rule.MITRE) > 0 {
		alert.MITRE = strings.Join(rule.MITRE, ",")
	}

	// Extract source and destination from record
	alert.SrcIP = record.Src()
	alert.DstIP = record.Dst()

	// Try to marshal the record as JSON for context
	recordJSON, err := json.Marshal(record)
	if err == nil {
		alert.MatchedRecord = string(recordJSON)
	}

	return alert, nil
}

// parseRecordType converts a type string (e.g., "TCP", "HTTP") to types.Type.
func parseRecordType(typeStr string) (types.Type, error) {
	// Add NC_ prefix if not present
	if !strings.HasPrefix(typeStr, "NC_") {
		typeStr = "NC_" + typeStr
	}

	// Look up the type value
	typeValue, ok := types.Type_value[typeStr]
	if !ok {
		return 0, fmt.Errorf("unknown record type: %s", typeStr)
	}

	return types.Type(typeValue), nil
}

// ValidateSeverity checks if a severity string is valid.
func ValidateSeverity(severity string) bool {
	switch strings.ToLower(severity) {
	case "info", "low", "medium", "high", "critical":
		return true
	default:
		return false
	}
}
